// Generated by Ultimate_GMS2_Decompiler_v3.csx
gml_pragma("global", @'__init_d3d()');
gml_pragma("global", @'__init_global()');
gml_pragma("global", @'__global_object_depths()');
gml_pragma("global", @'function camerax_set(arg0)
{
    var __xpos = arg0
    var __ypos = camera_get_view_y(view_camera[0])
    camera_set_view_pos(view_camera[0], __xpos, __ypos)
}');
gml_pragma("global", @'function cameray_set(arg0)
{
    var __xpos = camera_get_view_x(view_camera[0])
    var __ypos = arg0
    camera_set_view_pos(view_camera[0], __xpos, __ypos)
}');

// GameSpecificData Enums
enum e__VW 
{
	XView = 0,
	YView = 1,
	WView = 2,
	HView = 3,
	Angle = 4,
	HBorder = 5,
	VBorder = 6,
	HSpeed = 7,
	VSpeed = 8,
	Object = 9,
	Visible = 10,
	XPort = 11,
	YPort = 12,
	WPort = 13,
	HPort = 14,
	Camera = 15,
	SurfaceID = 16,
}

enum e__BG 
{
	Visible = 0,
	Foreground = 1,
	Index = 2,
	X = 3,
	Y = 4,
	Width = 5,
	Height = 6,
	HTiled = 7,
	VTiled = 8,
	XScale = 9,
	YScale = 10,
	HSpeed = 11,
	VSpeed = 12,
	Blend = 13,
	Alpha = 14,
}

// Generic Enum Declaration
enum UnknownEnum 
{
	Value_0,
	Value_1,
	Value_2,
	Value_5 = 5,
	Value_6,
	Value_7,
	Value_8,
	Value_9,
	Value_10,
	Value_11,
	Value_12,
	Value_13,
	Value_14,
	Value_18 = 18,
	Value_22 = 22,
	Value_23,
	Value_25 = 25,
	Value_26,
	Value_28 = 28,
	Value_29,
	Value_932 = 932,
	Value_933,
	Value_934,
	Value_935,
	Value_936,
	Value_937,
	Value_938,
	Value_939,
}